version: "3"

services:
  api-local:
    build: .
    environment:
      PORT: 80
      MONGO_CLUSTER_URL: mongodb://root:example@mongo:27017
      MONGO_DATABASE: local
    ports:
      - "8081:80"
    command: mvn exec:java -Dpersistence=mongo

  api-remote:
    image: ghcr.io/test-glo-2003/test_cd:remise3
    environment:
      PORT: 80
      MONGO_CLUSTER_URL: mongodb://root:example@mongo:27017
      MONGO_DATABASE: local
    ports:
      - "8082:80"
    command: mvn exec:java -Dpersistence=mongo

  mongo:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: